### ISSUE TITLE
Moving sprite *only* when mouse is clicking on it

### ISSUE THREAD

**Issue by Souna** [OneLoneCoder/olcPixelGameEngine#103]
Hello,

I have a single sprite on screen and I am trying to make it so that when I press and hold on this particular sprite, I can move it with the mouse. I want this to happen *only* when I'm clicking on the sprite, not around it. The tutorial for "User Input" added functionality for controlling the ball with the mouse, although this piece of code only checks if the mouse is being held down, not whether you are actually pressing on the ball itself. The ball then simply teleports to where your mouse coords are. I am struggling to figure this out and would appreciate some help to point me in the right direction!

Code example in question:
```
// Cheat! Moving The Ball With Mouse

    if (GetMouse(0).bHeld)
    {
	vBall = { float(GetMouseX()), float(GetMouseY()) };
    }
```

**Comment by sounaa** [comment]
I understand this is probably a stupidly simple easy fix, but I'm a noob so I'm using that as my excuse. 😁

**Comment by toman222** [comment]
Check if the distance of `vBall` from the mouse position is smaller than the radius of the circle before moving.

**Comment by sounaa** [comment]
I am quite new to this so I wouldn't know how to check that. I am also not trying to move `vBall` but rather my own sprite on screen which looks like this:
![HwkisXF](https://user-images.githubusercontent.com/8890024/80029089-3b2ce880-84b4-11ea-9118-cce6cc92ee45.png)

Thank you

**Comment by OneLoneCoder** [comment]
What you are really asking is how do i detect my mouse is withing the rectangle I am drawing the sprite? Its a simple point vs rectangle test.

```cpp
if(mouse.x >= s.x && mouse.y >= s.y && mouse.x < (s.x + s.width) && mouse.y < (s.y + s.height))
{
// Mouse is in sprite area on screen
}
```

**Comment by sounaa** [comment]
That definitely clears it up. I had something similar but I've since deleted it since it wasn't exactly what I was looking to do.

I still seem to be struggling however. I am unable to access those sprite x,y members directly like that. Most likely because I am drawing it wrong in the first place. What I have is this:

OnUserCreate:
```
drawCoord = { ScreenWidth() / 2.0f, ScreenHeight() / 2.0f }; //this is a vf2d variable
sprTest = new olc::Sprite("spritelocation");  //sprite
decDemo = new olc::Decal(sprTest);  //decal
```

Inside OnUserUpdate:
```
DrawDecal(drawCoord, decDemo);
```
I can't simply just check sprTest.x or sprTest.y, because those don't exist for me. I'm having sort of a brain fart when it comes to this.

I do understand this displays a large lack of knowledge, but a push in the right direction would be greatly appreciated.

**Comment by toman222** [comment]
`s.x` and `s.y` in this case would be `drawCoord.x` and `drawCoord.y` respectively, since it's just the location that you're drawing to

**Comment by sounaa** [comment]
That did fix it, but only a little bit. When mouse is held down and is located within the sprite, the sprite will move to the mouse position. This is fine, except that the position of the sprite is considered the top left corner of it, so the mouse will suddenly be grabbing the top left corner of the sprite (the 0,0 position of it). 

If I wanted to move the sprite right or down, that's fine. The problem comes when I want to drag the sprite left, or up. It doesn't work anymore because when you do that the mouse is no longer considered "inside" the sprite, and so you aren't allowed to move it up or left.

Shouldn't there be a `pos.x` and `pos.y` property attached to any sprite the engine draws? Rather than tell it to use the location I'm drawing it to as the sprite location, I would like to just tell it to use `sprite.x` or `sprite.y`

Thank you for taking the time

**Comment by OneLoneCoder** [comment]
Consider a situation where you use the same sprite 10 times. Which position should the sprite adopt? My point is the sprite should not have position information, its simply an image. You are turning it into a more sophisticated interactive game object, which is cool, but your object should reference the sprite.

As for your problem with movement. Once you've determined the point is within the sprite rectangle, store the offset of the top left of the sprite to the mouse pointer. Then redraw the sprite at the mouse location subtracting that offset.
