### ISSUE TITLE
When to use decals vs sprites

### ISSUE THREAD

**Issue by arqlz** [OneLoneCoder/olcPixelGameEngine#104]
When drawing sprites they persist on screen, so an static scene will be very fast. Then drawing decals with consume a lot of cycles, so a complex scene can get an FPS drop.

How should I work with sprites/decals?

**Comment by OneLoneCoder** [comment]
Sprites are the actual "image data", they are the arrays of pixels that make up the image. Decals are a hook to a sprite, that lives on the GPU. Sprites are useful when constructing imagery programmatically, and so far have been fine for drawing to the screen. You can even DrawXXX() to a sprite!

Decals are useful for fast drawing of sprites, so things like explosions, where you may have numerous sprites, complex transparency effects, distortion of the sprite rectangle.

Sprites and DrawXXX() functions write into the memory surface that is drawn to the screen, so yes they are persistent. But this has its downsides, you have to clear sprites each frame in order to emulate movement.

Your approach is correct. Compose the static parts of your scene statically, so they dont need to be redrawn. And then draw the decals on top. As demonstrated in the video, there isn't a huge overhead in drawing a decal, so you can draw many thousands. 

You suggest you are getting an FPS drop. Dont use this as a performance metric - it's intuitively misleading. dropping from 5000fps to 4000fps, is nothing like dropping from 60fps to 30 fps, due to the relationship FPS = 1/Time Per Frame.
