### ISSUE TITLE
The pixel struct isn't portable due to endianness.

### ISSUE THREAD

**Issue by VireV** [OneLoneCoder/olcPixelGameEngine#164]
The Pixel struct uses a union of a uint32_t and a struct containing the rgba values. The problem is that the order of the rgba values in memory will be reversed on Big Endian architectures(x86 uses little endian). This means that assigning them as a uint32_t will manipulate the wrong subpixels. Maybe the endianness could be detected at compile time and the struct rgba values could be declared in the reversed order to counteract this. 

Thanks.

**Comment by scripticuk** [comment]
Actually, given that the values are _always_ applied through the uint32_t value, then even specifying the R,G,B and A components separately would give the same result,

One could check for endianness when using the GCC compiler using __BYTE_ORDER__. I don't think that Visual Studio offers any way to detect endianness at compile time. Let's face it if you're compiling for anything other than Windows you're probably using GCC, and if you're compiling for anything more exotic you're going to be checking for this sort of thing anyway.

I'm not sure how often anyone will find themselves compiling on a big-endian architecture (possibly ARM?), but this should cover most cases:
`
struct Pixel
{
	union
	{
		uint32_t n = nDefaultPixel;
        #ifdef __BYTE_ORDER__
        #if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
  			struct { uint8_t a; uint8_t b; uint8_t g; uint8_t r; };
        #endif
        #else
			struct { uint8_t r; uint8_t g; uint8_t b; uint8_t a; };
        #endif
	};

	enum Mode { NORMAL, MASK, ALPHA, CUSTOM };

	Pixel();
	Pixel(uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha = nDefaultAlpha);
	Pixel(uint32_t p);
	bool operator==(const Pixel& p) const;
	bool operator!=(const Pixel& p) const;
};


Pixel::Pixel(uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha)
{
    #ifdef __BYTE_ORDER__
    #if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
   		n = alpha | (blue << 8) | (green << 16) | (red << 24);
    #endif
    #else
		n = red | (green << 8) | (blue << 16) | (alpha << 24);
    #endif
}
`

You'd certainly want to test this though because I haven't ;)

**Comment by moderah** [comment]
MN

**Comment by VireV** [comment]
If you defined the order of the rgba pixels reversed in the class, I don't think you would have to change the implementation? Since the rest of the implementation will access the reversed subpixels?

**Comment by OneLoneCoder** [comment]
A quick thought on this - I can only see it being applicable if your application crosses an endian domain somehow. Images etc, have a defined byte order, and the platforms that load them take this into account.
