### ISSUE TITLE
Sprite has no copy-constructor

### ISSUE THREAD

**Issue by joshinils** [OneLoneCoder/olcPixelGameEngine#18]
I created a custom class which has a sprite as a member and is able to draw itself, a Tile.

I then created temporary copies of my tiles and put them in vectors, these temporaries get deleted, and their copy (implicitly a copy of all its members like position, and the sprite, is created).
then the scope of the temporary ran out and it got deleted along with its sprite.

Now i wanted to use the copy of my tile and draw the sprite, but alas the pColData doesn't point to anything valid any more, as it got deleted by the destruction of the temporary Tile object.

After i found out, i wrote a simple copy constructor for sprites and it works fine.

see [my code](https://github.com/joshinils/minesweep/commit/b6fd7da8be00f29ab77896585c678f25ca725eae#r31929683) for more details.

**Comment by OneLoneCoder** [comment]
This issue was discussed at length on the Discord server. The result was its easy enough to add one if you require it for your needs, but those needs may be quite exceptional as it is discouraged to have multiple copies of the same sprite. On the whole, no real conclusion, and thanks to Josh for prompting the discussion and providing interesting use cases for its application.
