### ISSUE TITLE
Second Network Client Closes when First Closes

### ISSUE THREAD

**Issue by MrFlick** [OneLoneCoder/olcPixelGameEngine#184]
I was following along with the samples networking code at olcPixelGameEngine/Videos/Networking/Parts1&2/

I found that when I launch (double click) the server, and then launch (double click) 2 clients (A then B). If I close A by pressing 3, then B will also close. But if I close B (again by pressing 3), then A will stay open.

If you open more than two clients, all clients opened after the one where you press 3 also close.

Oddly, It seems not to happen when you just close window A (Alt-F4 or click the close icon on the window). It also doesn't seem to happen if I run the clients from inside an existing command prompt window. So maybe this is just a Windows windowing issue?

Compiled with 

g++.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0

on Windows 10 (version 2004) using

g++ -g -std=c++17 -I . -I ..\..\asio-1.18.0\include SimpleServer.cpp -o SimpleServer.exe -lws2_32 -lwsock32
g++ -g -std=c++17 -I . -I ..\..\asio-1.18.0\include SimpleClient.cpp -o SimpleClient.exe -lws2_32 -lwsock32

I was unable to figure out why it was happening. I wasn't sure if this was one of the issues you were already aware of.

Thanks for the series. I'm really enjoying it.

**Comment by OneLoneCoder** [comment]
Heh... this isnt an "issue" as such. What happens is you press "3" to close the window - but I use GetAsyncKeyState() to get the instantaneous state of the key on the window under focus. This is not the same as a "press event". Thus, the current window closes - focus transfers to a different window, "3" is still pressed (because your computer is faster than your fingers) and subsequently that window closes also, and so on until all the windows are closed (likely) or you lift your finger from the key.

**Comment by MrFlick** [comment]
That makes total sense. Never considered that and it seems so obvious now. Cheers!
