### ISSUE TITLE
Some system might reject NPOT texture

### ISSUE THREAD

**Issue by mahiuchun** [OneLoneCoder/olcPixelGameEngine#194]
NPOT stands for Non-Power-Of-Two https://www.khronos.org/opengl/wiki/NPOT_Texture

My system uses Snapdragon 850 SoC. It is a Windows on ARM device.

I built https://github.com/OneLoneCoder/olcPixelGameEngine/wiki/Hello-World using x86 config. (x64 would not run through emulation; ARM64 config failed due to opengl32.lib not available).

And I got a plain white window.
<img width="769" alt="NPOT" src="https://user-images.githubusercontent.com/1404381/99216063-90e71c00-2789-11eb-9d94-3a3f1e91549d.png">

I used Windows x86 version of https://github.com/apitrace/apitrace which showed that all glTexImage2D calls have failed.

So I guessed 240 being NPOT was the issue and changed it to 128. And it worked
<img width="769" alt="POT" src="https://user-images.githubusercontent.com/1404381/99216308-3601f480-278a-11eb-8dae-ff7ab368cfb7.png">

To resolve this in general would require us to use next power of 2 sizes in textures and adjust texture coordinates accordingly.

**Comment by OneLoneCoder** [comment]
Since the next PGE will introduce an OGL 3.3 renderer, I will leave it to the user to facilitate support for NPOT systems. On the whole, in my video and documentation output I tend to use POT textures anyway. However, I think this is important enough to be mentioned prominently in the header file itself, so I will add it there.
