### ISSUE TITLE
olcPixelGameEngine.h:3013:11: fatal error: GL/gl.h: No such file or directory

### ISSUE THREAD

**Issue by AmalIrfan** [OneLoneCoder/olcPixelGameEngine#206]
I was trying to run the [olcNES Part #2 code](https://github.com/OneLoneCoder/olcNES/blob/master/Part%232%20-%20CPU/olcNes_Video1_6502.cpp), I am new to c and cpp so I don't know how exactly header files work. I read from the documentation that I just have to include the olcPixelGameEngine.h and it will work. Is there something else todo.

command: `g++ olcNes_Video1_6502.cpp -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17`

Error: 
```In file included from olcNes_Video1_6502.cpp:81:
olcPixelGameEngine.h:3013:11: fatal error: GL/gl.h: No such file or directory
 3013 |  #include <GL/gl.h>
      |           ^~~~~~~~~
compilation terminated.```

**Comment by Vallerious** [comment]
I had a similar problem in another project and used [this ](https://www.c-sharpcorner.com/UploadFile/f5a10c/getting-started-with-opengl-in-visual-cpp/)tutorial to fix it.
Basically, you have to download the OpenGL on your computer so that your project can work with it - there is an important step in which you include additional directories to your project linker. There are also a few places in your drive that you have to setup the libraries.
I am a beginner in C++ myself and do not know if all steps are neccessary!
Good luck!

**Comment by KrossX** [comment]
Linux? You're missing the OpenGL headers. I don't what distribution you're using, but Ubuntu had a build-essential and that was enough if I remember correctly. Otherwise, try installing the mesa-common or libmesa dev packages.

**Comment by Moros1138** [comment]
If you're using Linux, check out [Compiling on Linux](https://github.com/OneLoneCoder/olcPixelGameEngine/wiki/Compiling-on-Linux)

**Comment by AmalIrfan** [comment]
Thanks, now it works I had to install some dev packages mentioned in documentation. [Compiling with linux](https://github.com/OneLoneCoder/olcPixelGameEngine/wiki/Compiling-on-Linux)
`sudo apt install build-essential libglu1-mesa-dev libpng-dev`
Thank you very much.

I was doing the breakout clone tutorial in the wiki, it seems to be missing some files, could you recommend any tutorials.
