### ISSUE TITLE
potential for exceptions/crashes in tsqueue (olcPGEX_Network)

### ISSUE THREAD

**Issue by HerrDingenz** [OneLoneCoder/olcPixelGameEngine#268]
since the thread-safe queue in the network extension can be used outside of the network framework, too - there should be guarding when using the front, back, pop_front and pop_back functions!

https://github.com/OneLoneCoder/olcPixelGameEngine/blob/7a20524ae4725120b38b9967583ff1c1e08da286/Extensions/olcPGEX_Network.h#L198-L295

i know the olc network framework prevents crashes by checking if the queue is empty before accessing those functions, but a user can create a tsqueue with his own type (just to have a thread-safe queue) and use it.

like:
```
olc::net::tsqueue<MYTYPE> queue;
auto test = queue.front();
```
in this case the queue is empty at that point and an exception will be thrown!

some guarding like:
```
const T& front()
{
	std::scoped_lock lock(muxQueue);
	if (!deqQueue.empty) return deqQueue.front();
	else return nullptr;
}
```
might come in handy to make the thread-safe queue more usable outside the olc::net framework.

Just a thought, though ;)

**Comment by kevlu123** [comment]
Personally, I would think of tsqueue as a thread safe wrapper around std::deque and I would expect front() and back() to behave exactly the same as the standard container. The standard defines the behaviour as undefined if the container is empty so I wouldn't mind an exception being thrown in tsqueue instead.

I don't think nullptr should be returned because that means that the return type would have to be changed to a pointer and this makes the code on the users' side less 'nice'. Considering that front() and back() being called on an empty container is almost always a programmer error, there's not much point in handling a nullptr case. It'd be like changing std::vector<T>::operator[] to possibly return nullptr when the index is out of range.

**Comment by HerrDingenz** [comment]
well .. looking at the MSVC implementation of std::deque they actually do a check if the deque is emtpy or not:

```
    _NODISCARD reference front() noexcept /* strengthened */ {
#if _CONTAINER_DEBUG_LEVEL > 0
        _STL_VERIFY(!empty(), "front() called on empty deque");
#endif // _CONTAINER_DEBUG_LEVEL > 0

        return *_Unchecked_begin();
    }

    _NODISCARD const_reference front() const noexcept /* strengthened */ {
#if _CONTAINER_DEBUG_LEVEL > 0
        _STL_VERIFY(!empty(), "front() called on empty deque");
#endif // _CONTAINER_DEBUG_LEVEL > 0

        return *_Unchecked_begin();
    }

    _NODISCARD reference back() noexcept /* strengthened */ {
#if _CONTAINER_DEBUG_LEVEL > 0
        _STL_VERIFY(!empty(), "back() called on empty deque");
#endif // _CONTAINER_DEBUG_LEVEL > 0

        return *_Prev_iter(_Unchecked_end());
    }

    _NODISCARD const_reference back() const noexcept /* strengthened */ {
#if _CONTAINER_DEBUG_LEVEL > 0
        _STL_VERIFY(!empty(), "back() called on empty deque");
#endif // _CONTAINER_DEBUG_LEVEL > 0

        return *_Prev_iter(_Unchecked_end());
    }
```
but they only do so if _CONTAINER_DEBUG_LEVEL >0 .. otherwise they return "unchecked pointers" to either iterator_begin or iterator_end
