### ISSUE TITLE
Question: How can I draw a rectangle around my mouse without drawing it directly on to my main screen?

### ISSUE THREAD

**Issue by AmitDavidi** [OneLoneCoder/olcPixelGameEngine#282]
Hello, I'm drawing the mandelbrot set which is heavily computational, So I want to draw a rectangle around my mouse on a "different layer". If I'm currently drawing the rectangle, I can't clear it without smearing it and destroying the main image of the mandelbrot set:

```
// this is in OnUserUpdate
		int X_pos = GetMouseX();
		int y_pos = GetMouseY();

		DrawRect(X_pos -zoom, y_pos -zoom, 2*zoom, 2*zoom, olc::GREY);

```

the mandelbrot set image created only when (in OnUserUpdate) a flag is set to 1 (after I click on screen for example). so normaly after creating the image I would not process the image again and again, so drawing the rectangle on it directly is not a valid option.

Is there an option of drawing on different layers and clearing different layers ? 

What im currently doing (which gets me very bad performance) is drawing the mandelbrot image onto a sprite.
then - Clearing the screen - drawing the sprite, and drawing the rectangle - each frame.

**Comment by Jack-Punter** [comment]
To create a new layer for rendering to you can use the `uint32_t CreateLayer();` function. (iirc layers are bottom up with the default layer being 0). Then use the `void SetDrawTarget(uint8_t layer);` to set the new layer as the target for the drawing functions. 

Its been a while since I've worked with this so i could be forgetting a few details, but the the functionality you're asking about does exist.

**Comment by Joseph21-6147** [comment]
There's an explanation of the concept of layering and how to implement this in the YT video on the PGE v 2.0 - https://youtu.be/8OfgGUGP4Vc?t=1054
