### ISSUE TITLE
can't compile with Windows.h

### ISSUE THREAD

**Issue by knn217** [OneLoneCoder/olcPixelGameEngine#313]
I only created an empty main function to test compilation :
---------------------------------------------------------------------------------------------
#include <iostream>
#include <string>
#include <Windows.h>
#define OLC_PGE_APPLICATION
#include "D:\UNREAL ENGINE 5 projects\VisualStudioHeader\olcPixelGameEngine.h"

int main()
{
	return 0;
}
---------------------------------------------------------------------------------------------
But i got compile error, it only works after i delete line 3: #include <Windows.h>
Anyone knows why this happened?

**Comment by ezyb** [comment]
if you copy pasted your include directives as they are, your first two lines are syntactically incorrect. Otherwise, as @Moros1138 said, Windows.h itself includes a lot of stuff internally which can interfere with PGE's includes, also try to put the line  `#define WIN32_LEAN_AND_MEAN` just before `#include <Windows.h> 
 
 ...
#define WIN32_LEAN_AND_MEAN
 #include <Windows.h>
...

**Comment by knn217** [comment]
I see, thanks for the replies!
