### ISSUE TITLE
Compile on Linux

### ISSUE THREAD

**Issue by jesusrp98** [OneLoneCoder/olcPixelGameEngine#42]
Is there a simple way to compile the 'CarCrimeCity' example in a Linux system?

**Comment by NaturalTangent** [comment]
I'm using Linux Mint Debian Edition (amd64). As far as I can remember, I made the following changes to build;

**_Part1_**
Edit olcPGEX_Graphics3D.h. Add the following to the includes near the top;
`#include <cstring>`

I had to install some dependencies by executing the following, I'm not sure if all of the open gl libs are required - I was too lazy to investigate (you may have to install more dependencies because I'm not sure what I already had installed);

`sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev libpng-dev`

Build using;

`g++ -o CarCrimeCity cCarCrimeCity.cpp -lX11 -lGL -lpthread -lpng -I.`


**_Part2_**
Edit olcPGEX_Graphics3D.h. Add the following to the includes near the top;

`#include <cstring>`

Edit olcPGEX_Graphics3D.h, around line 206 and add an extra '1.0' to the dir parameter;

`void SetLightSource(uint32_t nSlot, uint32_t nType, olc::Pixel col, olc::GFX3D::vec3d pos, olc::GFX3D::vec3d dir = { 0.0f, 0.0f, 1.0f, 1.0f }, float fParam = 0.0f);`

The version of lua in the repo appeared to be incomaptible with my system, so I installed the following;

`sudo apt-get install liblua5.3-dev`

 
Build using;

`g++ -o CarCrimeCity cCarCrimeCity.cpp cAutomata.cpp cCell_Building.cpp cCell.cpp cCell_Plane.cpp cCell_Road.cpp cCell_Water.cpp cCityMap.cpp cGameSettings.cpp main.cpp olcPixelGameEngine.cpp -lX11 -lGL -lpthread -lpng -llua5.3 -I.`

**Comment by jesusrp98** [comment]
Thanks, that helped!

**Comment by laurinneff** [comment]
I had to add -lstdc++fs to the g++ arguments (Manjaro, G++ 9.3.0)
