### ISSUE TITLE
Question about guidance and advice

### ISSUE THREAD

**Issue by AyushKool** [OneLoneCoder/olcPixelGameEngine#67]
Hi OneLoneCoder, I have been following you for a while now and watching your videos on youtube is a delight and also an inspiration. I am a beginning programmer and I am currently learning CPP on my own. I had a few questions that if you could answer would really help me in my coding journey:

- First, In every c++ tutorial I find, they teach the basics of C++ and then move data structures or projects where they use pre-made header files for almost everything. I want to learn how to make those header files from basic as you did in your PixelGameEngine and ConsoleGameEngine. 

- Secondly, I am currently working on making a 2D/3D graphing calculator in c++ but I am having trouble finding resources that help teach how to do this.

It would be a real help if you could refer me to some resources that deal with these things and also offer me some advice on how to make projects like you did.

Thank you for taking the time to read my request!

**Comment by OneLoneCoder** [comment]
Thanks Ayush,
The trick to making libraries is to first use them, so you can learn about their structure, what's good, what's bad, and what features it lacks. With that experience you can start writing your own. This works because to use a library properly, it helps to understand how the library works, and so spending time with it will expose you to the underlying technologies it is abstracting.

As for general advice, the best I can offer is be patient and practice loads. I know that's not what anybody wants to hear, but it takes time to gain experience and expertise. Nobody became "good" overnight, and everybody had to start somewhere.

Regarding your calculator project, first break it down into its two main components - parsing the user requested function to be graphed (consider the shunting yard algorithm perhaps), and displaying the graph. The former may be quite difficult depending upon your ability, but displaying stuff is a great way to learn about other libraries, such as OpenGL, SDL, SFML, and is often quite fun in the process. Heck, use olc::PixelGameEngine!
