### ISSUE TITLE
error C2872: 'byte': ambiguous symbol - Possible solution.

### ISSUE THREAD

**Issue by AlC65** [OneLoneCoder/olcPixelGameEngine#75]
If anyone is getting the 'byte': ambiguous symbol error message a possible solution is given here:
https://developercommunity.visualstudio.com/content/problem/93889/error-c2872-byte-ambiguous-symbol.html
If you declare 'using namespace std;' in your main.cpp place it after #include"olcPixelGameEngine.h".
This will place the declaration after #inlcude<windows.h> contained in olcPixelGameEngine.h.

#define OLC_PGE_APPLICATION
#include "olcPixelGameEngine.h"
using namespace std;

EDIT: This only applies to c++17 and up.

**Comment by n8behavior** [comment]
Great find!  Those are hard to track down. Which is why I just had to add a link to this great javidx9 video ;)
<a href="https://youtu.be/j0_u26Vpb4w?t=1330">
**Forbidden C++**
</a>
<a href="https://youtu.be/j0_u26Vpb4w?t=1330">
<img src="https://user-images.githubusercontent.com/692218/77833974-ada9e300-7117-11ea-9005-5257b158b4d5.png" height="200">
</a>

Love the channel, the work, and community...keep it coming!!

**Comment by OneLoneCoder** [comment]
Im gonna regret making that video aren't I? XD

**Comment by OneLoneCoder** [comment]
Tidying up so closing this.
